# Generated by Django 5.1.3 on 2024-12-16 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture6', '0004_card_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
